version: "3.9"

services:
  mongo:
    image: mongo:4.2
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: nodeauth
      MONGO_INITDB_ROOT_USERNAME: nodeauth
      MONGO_INITDB_ROOT_PASSWORD: nodeauth
    volumes:
      - .:/usr/mongo/data

  api:
    build: ./backend
    command: yarn start
    container_name: api
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    ports:
      - 3982:3982
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  app:
    build: ./frontend
    container_name: app
    environment:
      - DB_SERVER=kanban-postgres
    ports:
      - 80:80
    depends_on:
      - api
